#!/usr/bin/guile -s
!#

(use-modules (srfi srfi-64))
(use-modules (tuile pr))
(use-modules (tuile re))
(use-modules (tuile utils))

(add-to-load-path "..")
(use-modules (tuile edit))

(test-begin "edit")

(define testfile "/tmp/edit-input-test-file.txt")

(lines->file testfile (for-n (i 10) (ss "Line " (1+ i))))

(define s (read testfile))


;; ------------------------------------------------------------
;; Test diff jumping commands and their return values:

(test-equal 1 (line s))
(test-equal #f (edited? s))
(test-equal #f (not (match? s "Line 1")))

(step s)
(test-equal 2 (line s))
(step s -1)
(test-equal 1 (line s))
(step s)
(test-equal 2 (line s))
(step s -1)
(test-equal 1 (line s))
(line s 5)
(test-equal 5 (line s))
(firstline s)
(test-equal 1 (line s))
(lastline s)
(test-equal 10 (line s))


;; ------------------------------------------------------------
;; Test searching:

(firstline s)
(test-equal #t (search s "Line 1"))
(firstline s)
(test-equal #t (search s "Line 2"))
(line s 4)
(test-equal #f (search s "Line 3"))
(firstline s)
(search s "Line 1")
(test-equal 1 (line s))
(search s "Line 2")
(test-equal 2 (line s))
(search s "ne 8")
(search s "Line 8")

(let ((l (excursion s (lambda (s)
                      (search s "Line 9")
                      (line s)))))
  (test-equal 8 (line s))
  (test-equal 9 l))

(let ((found-it #f))
  (edit-catch #t
              (find s "Line 2")
              (set! found-it #t))
  (test-equal #f found-it))

(let ((found-it #f))
  (with-exception-handler
      (lambda (exn)
        #f)
    (lambda ()
      (edit-catch 'edit-search-error
                  (find s "Line 2")
                  (set! found-it #t))))
  (test-equal #f found-it))

(let ((found-it #f))
  (edit-catch #f
              (find s "Line 9")
              (set! found-it #t))
  (test-equal #t found-it))


;; ------------------------------------------------------------
;; Test content queries:

(firstline s)
(test-equal "Line 1" (get s))
(test-equal "Line 10" (ref s 10))
(test-equal #f (ref s 11))
(test-equal 1 (line s))
(test-equal '("Line 1" "Line 2") (ref s 1 2))


;; ------------------------------------------------------------
;; Test content manipulation:
(let ((l (get s)))
  (set s "foobar")
  (test-equal "foobar" (get s))
  (set s l)
  (test-equal 10 (linecount s))

  (update s (lambda (c)
            (re-sub "ne" c "en")))
  (test-equal "Lien 1" (get s))
  (set s l))

(insert s "Line -1")
(test-equal 11 (linecount s))
(test-equal "Line -1" (get s))
(remove s)
(test-equal 10  (linecount s))
(test-equal "Line 1"  (get s))

(let ((c '("foo" "bar")))
  (insert s c)
  (test-equal 12 (linecount s))
  (test-equal c (ref s 1 2))
  (remove s 2)
  (test-equal 10 (linecount s))

  (insert-step s "foo" 'end)
  (test-equal "foo" (get s))
  (insert-step s "bar" 'after)
  (test-equal "bar" (get s))
  (test-equal 12 (linecount s))
  (test-equal c (ref s 11 12))
  (test-equal (linecount s) (line s))
  (insert s c 'end)
  (test-equal 14 (linecount s))
  (test-equal c (ref s 13 14))
  (line s 11)
  (remove s 4))

(let ((len (linecount s)))
  (insertfile s testfile 'first)
  (test-equal (* 2 len) (linecount s))
  (insertfile s testfile 'end)
  (test-equal (* 3 len) (linecount s)))

(from-to s
         'first
         'last
         (lambda (s)
           (sub s "Line" "foobar")))
(test-equal '("foobar 5" "foobar 6") (ref s 5 6))


;; (do-all s
;;  (lambda ()
;;    (sub "Line" "foobar")))
;; (test-equal #("foobar 5" "foobar 6") (get-range s 5 6))
;; (blockline s)
;; (test-equal 30 (line))
;;
;; (do-range s 1 (linecount s)
;;           (lambda ()
;;             (sub s "foobar" "Line")))
;; (test-equal #("Line 5" "Line 6") (get-range s 5 6))
;; (blockline s)
;; (test-equal 30 (linecount s))
;; (test-equal 30 (line s))
;;
;; (do-for s 1 (linecount s)
;;         (lambda ()
;;           (sub "Line" "foobar")))
;; (test-equal #("foobar 5" "foobar 6") (get-range s 5 6))


;; ------------------------------------------------------------
;; Test misc commands:

(let ((org-lines (lines s)))
  (clear s)
  (test-equal '() (lines s))
  (test-equal #t (edited? s))

  (insert s org-lines)

  (mark s)
  (step s)
  (test-equal 2 (line s))
  (markgo s)
  (test-equal 1 (line s)))


;; ------------------------------------------------------------
;; Test file saving:

(let ((ofile "/tmp/edit-output-test-file.txt")
      (r2 #f)
      (r3 #f))
  (save s ofile)

  (let ((org-lines (lines s)))
    (set! r2 (read ofile))
    (test-equal org-lines (lines r2)))

  (set! r3 (read testfile))
  (save r3 ofile)
  
;;   (edit-use s r2
;;             (lines (edit-use s r3 (lines s)))
;;             (write-file s))

  (test-equal 0 (system (ss "diff " testfile " " ofile)))

  (when (file-exists? ofile)
    (delete-file ofile)))


;; ------------------------------------------------------------
;; Test Edit.edit:

;; (let ((ofile "/tmp/edit-output-test-file.txt"))
;;   (edit s ofile
;;         (insert s "foobar"))
;;   (edit-edit s ofile
;;                (test-equal "foobar" (get s)))
;;   (when (file-exists? ofile)
;;     (delete-file ofile)))


(when (file-exists? testfile)
  (delete-file testfile))

(test-end)
