#!/usr/bin/guile -s
!#

;;; ------------------------------------------------------------
;;; Trials for como-actions feature.


(add-to-load-path "..")

(use-modules (tuile como))
(use-modules (tuile pr))

(define (create)
  (pr (ss "touch " (como-var "file"))))

(define (delete)
  (pr (ss "rm -f " (como-var "file"))))


(como-actions "como-actions" "Tero Isannainen" "2020"
              '(
                [action    create    "Create file."]
                [action    delete    "Delete file."]
                [option    file      "File name."       "foobar.txt"]
                [option    dir       "Directory."       "."]
                [default   -         "Rest of the arguments."]
                )
              #:revert 'create)
