#!/usr/bin/guile -s
!#

(use-modules (ubu))

(define usr-install-path (car (string-split (getenv "GUILE_LOAD_PATH") #\:)))

(ubu-default "install")
(action install
 (sh "cp -r tuile" usr-install-path))

(action test-pr
        (with-output
         (sh "cd test; test-pr")))

(action test-como
        (with-output
         (sh "cd test; test-como")))

(action test-fn
        (with-output
         (sh "cd test; test-fn")))

(action test-graph
        (with-output
         (sh "cd test; test-graph")))

(action test-all
        (test-pr)
        (test-como)
        (test-fn)
        (test-graph))

(action clean
        (sh "rm -f test/*.log"))

(ubu-run-cli)
